In [5]:
import numpy as np

import cv2

print(np, version)

NameError: name 'version' is not defined

In [7]:
lista = (1, 2, 'a', 'b', 10, 10)

In [2]:
tupla = (1,2)

In [3]:
tupla[0,2]

TypeError: tuple indices must be integers or slices, not tuple

In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr1 + arr2

array([5, 7, 9])

In [8]:
np.array(lista)

array(['1', '2', 'a', 'b', '10', '10'], dtype='<U21')

In [10]:
zeros = np.zeros((2, 3))
ones = np.ones((2,3))
arange = np.arange(1, 9, 2)
#linspace = np.linspace()

print(zeros)
print(ones)
print(arange)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7]


In [12]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([10, 20, 30])

array1 + array2

array([[11, 22, 33],
       [14, 25, 36]])