In [1]:
import numpy as np

list1 = [1, 2, 3]
list2 = [4, 5, 6]
result = []

for i in range(len(list1)):
    result.append(list1[i] + list2[i])

print(result)


[5, 7, 9]


In [2]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = []

result = array1 + array2
print(result)

[5 7 9]


In [7]:
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
arange = np.arange(1, 9, 2)
linspace = np.linspace(0, 1, 5)

print(zeros)
print(ones)
print(arange)
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7]
[0.   0.25 0.5  0.75 1.  ]


In [9]:
array1 = np.array(list1)

In [10]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)

print(array1 * array2)

[5 7 9]
[ 4 10 18]


In [13]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([10, 20, 30])

print(array1 + array2)
print(array1 * array2)


[[11 22 33]
 [14 25 36]]
[[ 10  40  90]
 [ 40 100 180]]


In [15]:
array = np.array([1, 2, 3, 4, 5])

sum = np.sum(array)
mean = np.mean(array)
std = np.std(array)
max = np.max(array)
min = np.min(array)

print(sum)
print(mean)
print(std)
print(max)
print(min)

15
3.0
1.4142135623730951
5
1


In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array[0, 1])
print(array[0, :])
print(array[1, :])
print(array[:, 0])
print(array[:, 0:2])

2
[1 2 3]
[4 5 6]
[1 4]
[[1 2]
 [4 5]]


In [17]:
array = np.array([1, 2, 3, 4, 5])
print(array[array < 3])
print(array[array == 5])

[1 2]
[5]


In [19]:
array = np.array([[[1], [2]], [[3], [4]]])

print(array[0, 0, 0])
print(array[0, :, 0])
print(array[:, 0, 0])
#print(array[0, 0, 1])
print(array[..., 0])

array = np.array([1, 2, 3, 4, 5])
print(array[::2])
print(array[::-1])

1
[1 2]
[1 3]
[[1 2]
 [3 4]]
[1 3 5]
[5 4 3 2 1]


In [24]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

#Producto punto
print(np.dot(array1, array2))

print(array1 @ array2)

#Transpuesta de una matriz
array = np.array([[1, 2], [3, 4]])
print(array.T)
print(np.transpose(array))

#Inversa de una matriz
print(np.linalg.inv(array))

#Determinante
print(np.linalg.det(array))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [29]:
#Random seed
np.random.seed(614)

# genera n (5) numeros aleatorios de [0.0, 1.0]
random = np.random.rand(5)
print(random)

#Enteros aleatorios
rand_int = np.random.randint(0, 10, size=(2, 3))
print(rand_int)

[0.84144643 0.61529076 0.07478831 0.19021926 0.71553527]
[[7 9 8]
 [2 8 1]]
